export const GET_REVIEWS = "GET_REVIEWS";
export const SET_REVIEWS = "GET_REVIEWS";
export const TOGGLE_REVIEWS_POPUP = "TOGGLE_REVIEWS_POPUP";
export const TOGGLE_REVIEWS_LOADER = "TOGGLE_REVIEWS_LOADER";
